package com.example.localization

enum class AppLanguage(val code: String, val displayName: String, val isRtl: Boolean = false) {
    ENGLISH("en", "English"),
    ARABIC("ar", "العربية (Arabic)", true),
    FRENCH("fr", "Français (French)"),
    SPANISH("es", "Español (Spanish)"),
    GERMAN("de", "Deutsch (German)"),
    TURKISH("tr", "Türkçe (Turkish)"),
    PORTUGUESE("pt", "Português (Portuguese)"),
    ITALIAN("it", "Italiano (Italian)"),
    CHINESE("zh", "中文 (Chinese)"),
    JAPANESE("ja", "日本語 (Japanese)")
}

data class LocalizedStrings(
    val appTitle: String,
    val appSubtitle: String,
    val navDashboard: String,
    val navAiAssistant: String,
    val navTravel: String,
    val navStudy: String,
    val navCareer: String,
    val navFinance: String,
    val navTasks: String,
    val navShopping: String,
    val navSettings: String,
    val todayOverview: String,
    val tasksRemaining: String,
    val activeReminders: String,
    val spentToday: String,
    val goalProgress: String,
    val askAiHint: String,
    val planAnythingPrompt: String,
    val createPlanButton: String,
    val applyPlanToLifeOs: String,
    val planAppliedSuccess: String,
    val addNewTask: String,
    val addNewTrip: String,
    val addNewGoal: String,
    val addTransaction: String,
    val totalBudget: String,
    val itinerary: String,
    val packingList: String,
    val usefulPhrases: String,
    val savingsGoals: String,
    val income: String,
    val expense: String,
    val currentBalance: String,
    val privacyHeader: String,
    val privacyClearData: String,
    val privacyClearWarning: String,
    val premiumTitle: String,
    val premiumBadge: String,
    val freeTier: String,
    val switchLanguage: String
)

object LocalizationManager {
    fun getStrings(lang: AppLanguage): LocalizedStrings {
        return when (lang) {
            AppLanguage.ARABIC -> LocalizedStrings(
                appTitle = "LifeOS",
                appSubtitle = "مساعدك الذكي لإدارة وتنظيم كل تفاصيل حياتك",
                navDashboard = "الرئيسية",
                navAiAssistant = "المساعد الذكي",
                navTravel = "السفر",
                navStudy = "الدراسة",
                navCareer = "العمل والمهنة",
                navFinance = "المالية",
                navTasks = "المهام",
                navShopping = "التسوق",
                navSettings = "الإعدادات",
                todayOverview = "نظرة اليوم الذكية",
                tasksRemaining = "مهام متبقية",
                activeReminders = "تذكير نشط",
                spentToday = "تم إنفاقه اليوم",
                goalProgress = "تقدم الأهداف",
                askAiHint = "اكتب ما تريد بلغتك وسأحوله لخطة عملية...",
                planAnythingPrompt = "خطط لأي شيء بالذكاء الاصطناعي",
                createPlanButton = "توليد خطة ذكية",
                applyPlanToLifeOs = "تطبيق الخطة في LifeOS",
                planAppliedSuccess = "تم حفظ الخطة وإضافتها إلى مهامك وجداولك بنجاح!",
                addNewTask = "إضافة مهمة جديدة",
                addNewTrip = "إضافة رحلة جديدة",
                addNewGoal = "إضافة هدف ادخار",
                addTransaction = "تسجيل معاملة مالية",
                totalBudget = "الميزانية الكلية",
                itinerary = "الجدول اليومي",
                packingList = "قائمة الأمتعة",
                usefulPhrases = "العبارات والترجمة",
                savingsGoals = "أهداف الادخار",
                income = "دخل",
                expense = "مصروف",
                currentBalance = "الرصيد التقديري",
                privacyHeader = "الأمان والخصوصية المحلية",
                privacyClearData = "مسح جميع بياناتي",
                privacyClearWarning = "سيتم حذف كافة البيانات من الهاتف بشكل دائم.",
                premiumTitle = "ترقية LifeOS Pro",
                premiumBadge = "نسخة مجانية معقولة",
                freeTier = "الخطة الحالية: مجانية",
                switchLanguage = "اختر اللغة المفضلة"
            )
            AppLanguage.FRENCH -> LocalizedStrings(
                appTitle = "LifeOS",
                appSubtitle = "Votre assistant de vie intelligent tout-en-un",
                navDashboard = "Tableau de bord",
                navAiAssistant = "Assistant IA",
                navTravel = "Voyages",
                navStudy = "Études",
                navCareer = "Carrière",
                navFinance = "Finances",
                navTasks = "Tâches",
                navShopping = "Achats",
                navSettings = "Paramètres",
                todayOverview = "Aperçu du jour",
                tasksRemaining = "Tâches restantes",
                activeReminders = "Rappels actifs",
                spentToday = "Dépensé aujourd'hui",
                goalProgress = "Objectifs de la semaine",
                askAiHint = "Décrivez votre projet en langage naturel...",
                planAnythingPrompt = "Planifiez n'importe quoi avec l'IA",
                createPlanButton = "Créer le plan",
                applyPlanToLifeOs = "Intégrer dans LifeOS",
                planAppliedSuccess = "Plan intégré avec succès dans vos tâches !",
                addNewTask = "Nouvelle tâche",
                addNewTrip = "Nouveau voyage",
                addNewGoal = "Nouvel objectif",
                addTransaction = "Ajouter transaction",
                totalBudget = "Budget total",
                itinerary = "Itinéraire",
                packingList = "Valise & check-list",
                usefulPhrases = "Phrases utiles",
                savingsGoals = "Objectifs d'épargne",
                income = "Revenu",
                expense = "Dépense",
                currentBalance = "Solde calculé",
                privacyHeader = "Confidentialité & Sécurité",
                privacyClearData = "Supprimer mes données",
                privacyClearWarning = "Toutes les données locales seront définitivement effacées.",
                premiumTitle = "LifeOS Premium",
                premiumBadge = "Version Gratuite",
                freeTier = "Plan actuel : Gratuit",
                switchLanguage = "Changer la langue"
            )
            AppLanguage.SPANISH -> LocalizedStrings(
                appTitle = "LifeOS",
                appSubtitle = "Tu asistente inteligente de vida todo en uno",
                navDashboard = "Inicio",
                navAiAssistant = "Asistente IA",
                navTravel = "Viajes",
                navStudy = "Estudio",
                navCareer = "Carrera",
                navFinance = "Finanzas",
                navTasks = "Tareas",
                navShopping = "Compras",
                navSettings = "Ajustes",
                todayOverview = "Resumen de hoy",
                tasksRemaining = "Tareas pendientes",
                activeReminders = "Recordatorios",
                spentToday = "Gastado hoy",
                goalProgress = "Progreso de metas",
                askAiHint = "Dime qué necesitas en lenguaje natural...",
                planAnythingPrompt = "Planifica cualquier cosa con IA",
                createPlanButton = "Crear plan",
                applyPlanToLifeOs = "Aplicar a LifeOS",
                planAppliedSuccess = "¡Plan guardado e importado con éxito!",
                addNewTask = "Nueva tarea",
                addNewTrip = "Nuevo viaje",
                addNewGoal = "Nueva meta",
                addTransaction = "Registrar gasto/ingreso",
                totalBudget = "Presupuesto total",
                itinerary = "Itinerario diario",
                packingList = "Lista de equipaje",
                usefulPhrases = "Frases y traducción",
                savingsGoals = "Metas de ahorro",
                income = "Ingresos",
                expense = "Gastos",
                currentBalance = "Saldo actual",
                privacyHeader = "Privacidad y Seguridad",
                privacyClearData = "Borrar todos mis datos",
                privacyClearWarning = "Se eliminarán todos los registros locales de forma permanente.",
                premiumTitle = "LifeOS Premium",
                premiumBadge = "Plan Gratuito",
                freeTier = "Plan actual: Gratis",
                switchLanguage = "Cambiar idioma"
            )
            AppLanguage.GERMAN -> LocalizedStrings(
                appTitle = "LifeOS",
                appSubtitle = "Ihr intelligenter All-in-One Lebensassistent",
                navDashboard = "Dashboard",
                navAiAssistant = "KI-Assistent",
                navTravel = "Reisen",
                navStudy = "Lernen",
                navCareer = "Karriere",
                navFinance = "Finanzen",
                navTasks = "Aufgaben",
                navShopping = "Einkaufen",
                navSettings = "Einstellungen",
                todayOverview = "Heutige Übersicht",
                tasksRemaining = "Verbleibende Aufgaben",
                activeReminders = "Erinnerungen",
                spentToday = "Heute ausgegeben",
                goalProgress = "Wochenziele",
                askAiHint = "Beschreiben Sie, was Sie planen möchten...",
                planAnythingPrompt = "Plane alles mit intelligenter KI",
                createPlanButton = "Plan erstellen",
                applyPlanToLifeOs = "In LifeOS übernehmen",
                planAppliedSuccess = "Plan erfolgreich in LifeOS importiert!",
                addNewTask = "Neue Aufgabe",
                addNewTrip = "Neue Reise",
                addNewGoal = "Neues Sparziel",
                addTransaction = "Buchung eintragen",
                totalBudget = "Gesamtbudget",
                itinerary = "Tagesablauf",
                packingList = "Packliste",
                usefulPhrases = "Nützliche Redewendungen",
                savingsGoals = "Sparziele",
                income = "Einnahme",
                expense = "Ausgabe",
                currentBalance = "Kontostand",
                privacyHeader = "Datenschutz & Sicherheit",
                privacyClearData = "Alle Daten löschen",
                privacyClearWarning = "Alle lokalen Daten werden unwiderruflich gelöscht.",
                premiumTitle = "LifeOS Premium",
                premiumBadge = "Kostenlose Version",
                freeTier = "Aktueller Tarif: Kostenlos",
                switchLanguage = "Sprache wechseln"
            )
            AppLanguage.TURKISH -> LocalizedStrings(
                appTitle = "LifeOS",
                appSubtitle = "Akıllı hepsi bir arada kişisel yaşam asistanınız",
                navDashboard = "Genel Bakış",
                navAiAssistant = "Yapay Zeka",
                navTravel = "Seyahat",
                navStudy = "Eğitim",
                navCareer = "Kariyer",
                navFinance = "Finans",
                navTasks = "Görevler",
                navShopping = "Alışveriş",
                navSettings = "Ayarlar",
                todayOverview = "Bugünün Özeti",
                tasksRemaining = "Kalan Görevler",
                activeReminders = "Aktif Hatırlatıcılar",
                spentToday = "Bugün Harcanan",
                goalProgress = "Haftalık Hedefler",
                askAiHint = "Ne planlamak istediğinizi doğal dille yazın...",
                planAnythingPrompt = "Her Şeyi Yapay Zeka ile Planlayın",
                createPlanButton = "Plan Oluştur",
                applyPlanToLifeOs = "LifeOS'a Aktar",
                planAppliedSuccess = "Plan başarıyla görevlerinize eklendi!",
                addNewTask = "Yeni Görev",
                addNewTrip = "Yeni Gezi",
                addNewGoal = "Yeni Birikim Hedefi",
                addTransaction = "İşlem Ekle",
                totalBudget = "Toplam Bütçe",
                itinerary = "Günlük Program",
                packingList = "Bavul Listesi",
                usefulPhrases = "Faydalı Cümleler",
                savingsGoals = "Birikim Hedefleri",
                income = "Gelir",
                expense = "Gider",
                currentBalance = "Kalan Bakiye",
                privacyHeader = "Gizlilik ve Güvenlik",
                privacyClearData = "Tüm Verilerimi Sil",
                privacyClearWarning = "Tüm yerel veriler kalıcı olarak silinecektir.",
                premiumTitle = "LifeOS Premium",
                premiumBadge = "Ücretsiz Sürüm",
                freeTier = "Mevcut Plan: Ücretsiz",
                switchLanguage = "Dili Değiştir"
            )
            else -> LocalizedStrings(
                appTitle = "LifeOS",
                appSubtitle = "Your Intelligent Life Assistant",
                navDashboard = "Dashboard",
                navAiAssistant = "AI Assistant",
                navTravel = "Travel",
                navStudy = "Study",
                navCareer = "Career",
                navFinance = "Finance",
                navTasks = "Tasks",
                navShopping = "Shopping",
                navSettings = "Settings",
                todayOverview = "Today's Smart Overview",
                tasksRemaining = "tasks remaining",
                activeReminders = "important reminder",
                spentToday = "spent today",
                goalProgress = "Weekly goals progress",
                askAiHint = "Describe what you need in natural language...",
                planAnythingPrompt = "Plan Anything with LifeOS AI",
                createPlanButton = "Generate Action Plan",
                applyPlanToLifeOs = "Import Plan to LifeOS",
                planAppliedSuccess = "Plan successfully imported into your tasks & schedules!",
                addNewTask = "Add Task",
                addNewTrip = "New Trip",
                addNewGoal = "New Savings Goal",
                addTransaction = "Add Transaction",
                totalBudget = "Total Budget",
                itinerary = "Daily Itinerary",
                packingList = "Packing Checklist",
                usefulPhrases = "Useful Phrases & Translations",
                savingsGoals = "Savings Goals",
                income = "Income",
                expense = "Expense",
                currentBalance = "Estimated Balance",
                privacyHeader = "Privacy & Local Data Protection",
                privacyClearData = "Wipe All Local Data",
                privacyClearWarning = "All stored tasks, plans, and budgets will be permanently deleted from this device.",
                premiumTitle = "LifeOS Premium",
                premiumBadge = "Free Tier",
                freeTier = "Current Plan: Free with generous limits",
                switchLanguage = "App Language"
            )
        }
    }
}
